using System.Text;
using static Networker.Core.NetTools.Config.ConfigWriter;
using Networker.Core.Models.NetworkConfig;

namespace Networker.Core.NetTools.Config;

/// <summary>
/// Port of the Python <c>arista_eos.j2</c> Jinja2 template.
/// </summary>
internal static class AristaEosConfigTemplate
{
    public static string Render(NetworkDeviceConfig cfg)
    {
        var sb = new StringBuilder();
        W(sb, "!");
        W(sb, "! Generated by NetConfigPro");
        W(sb, "! Vendor: Arista EOS");
        W(sb, "!");
        W(sb, $"hostname {cfg.Hostname}");
        W(sb, "!");

        if (!string.IsNullOrEmpty(cfg.EnableSecret))
        {
            W(sb, $"enable secret sha512 {cfg.EnableSecret}");
        }

        if (!string.IsNullOrEmpty(cfg.DomainName))
        {
            W(sb, $"dns domain {cfg.DomainName}");
        }

        W(sb, "!");

        if (cfg.DnsServers.Count > 0)
        {
            foreach (var dns in cfg.DnsServers)
            {
                W(sb, $"ip name-server {dns}");
            }

            W(sb, "!");
        }

        if (cfg.NtpServers.Count > 0)
        {
            foreach (var ntp in cfg.NtpServers)
            {
                W(sb, $"ntp server {ntp}");
            }

            W(sb, "!");
        }

        if (!string.IsNullOrEmpty(cfg.BannerMotd))
        {
            W(sb, "banner motd");
            W(sb, cfg.BannerMotd);
            W(sb, "EOF");
        }

        W(sb, "!");

        if (cfg.Vlans.Count > 0)
        {
            foreach (var vlan in cfg.Vlans)
            {
                W(sb, $"vlan {vlan.VlanId}");
                W(sb, $"   name {vlan.Name}");
                if (vlan.State != "active")
                {
                    W(sb, $"   state {vlan.State}");
                }

                W(sb, "!");
            }
        }

        W(sb, "!");

        foreach (var iface in cfg.Interfaces)
        {
            W(sb, $"interface {iface.Name}");
            if (!string.IsNullOrEmpty(iface.Description))
            {
                W(sb, $"   description {iface.Description}");
            }

            W(sb, iface.Enabled ? "   no shutdown" : "   shutdown");

            if (iface.IpAddress is not null && iface.SubnetMask is not null)
            {
                W(sb, $"   ip address {iface.IpAddress}/{ConfigTemplateFilters.SubnetToCidr(iface.SubnetMask.ToString())}");
            }

            if (iface.IsTrunk)
            {
                W(sb, "   switchport mode trunk");
                if (iface.NativeVlan is not null)
                {
                    W(sb, $"   switchport trunk native vlan {iface.NativeVlan}");
                }

                if (!string.IsNullOrEmpty(iface.TrunkAllowedVlans))
                {
                    W(sb, $"   switchport trunk allowed vlan {iface.TrunkAllowedVlans}");
                }
            }
            else if (iface.VlanId is not null)
            {
                W(sb, "   switchport mode access");
                W(sb, $"   switchport access vlan {iface.VlanId}");
            }

            if (iface.Mtu != 1500)
            {
                W(sb, $"   mtu {iface.Mtu}");
            }

            if (iface.ChannelGroup is not null)
            {
                W(sb, $"   channel-group {iface.ChannelGroup} mode active");
            }

            W(sb, "!");
        }

        W(sb, "!");

        foreach (var acl in cfg.Acls)
        {
            W(sb, $"ip access-list {acl.Name}");
            foreach (var entry in acl.Entries)
            {
                if (!string.IsNullOrEmpty(entry.Remark))
                {
                    W(sb, $"   remark {entry.Remark}");
                }
                else
                {
                    var line = new StringBuilder();
                    line.Append("   ").Append(entry.Sequence).Append(' ')
                        .Append(ConfigTemplateFilters.AclActionValue(entry.Action)).Append(' ')
                        .Append(ConfigTemplateFilters.AclProtocolValue(entry.Protocol)).Append(' ')
                        .Append(entry.Source);
                    if (entry.SourceWildcard != "0.0.0.0")
                    {
                        line.Append('/').Append(ConfigTemplateFilters.SubnetToCidr(entry.SourceWildcard));
                    }

                    if (!string.IsNullOrEmpty(entry.SourcePort))
                    {
                        line.Append(" eq ").Append(entry.SourcePort);
                    }

                    line.Append(' ').Append(entry.Destination);
                    if (entry.DestinationWildcard != "0.0.0.0")
                    {
                        line.Append('/').Append(ConfigTemplateFilters.SubnetToCidr(entry.DestinationWildcard));
                    }

                    if (!string.IsNullOrEmpty(entry.DestinationPort))
                    {
                        line.Append(" eq ").Append(entry.DestinationPort);
                    }

                    if (entry.Log)
                    {
                        line.Append(" log");
                    }

                    W(sb, line.ToString());
                }
            }

            W(sb, "!");
        }

        W(sb, "!");

        foreach (var route in cfg.StaticRoutes)
        {
            var line = new StringBuilder();
            line.Append("ip route ").Append(route.Destination).Append('/')
                .Append(ConfigTemplateFilters.SubnetToCidr(route.Mask)).Append(' ').Append(route.NextHop);
            if (route.AdminDistance != 1)
            {
                line.Append(' ').Append(route.AdminDistance);
            }

            if (!string.IsNullOrEmpty(route.Name))
            {
                line.Append(" name ").Append(route.Name);
            }

            W(sb, line.ToString());
        }

        W(sb, "!");

        if (cfg.Ospf is not null)
        {
            W(sb, $"router ospf {cfg.Ospf.ProcessId}");
            if (!string.IsNullOrEmpty(cfg.Ospf.RouterId))
            {
                W(sb, $"   router-id {cfg.Ospf.RouterId}");
            }

            if (cfg.Ospf.ReferenceBandwidth != 100)
            {
                W(sb, $"   auto-cost reference-bandwidth {cfg.Ospf.ReferenceBandwidth}");
            }

            foreach (var passive in cfg.Ospf.PassiveInterfaces)
            {
                W(sb, $"   passive-interface {passive}");
            }

            if (cfg.Ospf.DefaultInformationOriginate)
            {
                W(sb, "   default-information originate");
            }

            foreach (var network in cfg.Ospf.Networks)
            {
                W(sb, $"   network {network.Network} {network.Wildcard} area {network.Area}");
            }

            W(sb, "!");
        }

        W(sb, "!");

        if (cfg.Bgp is not null)
        {
            W(sb, $"router bgp {cfg.Bgp.LocalAs}");
            if (!string.IsNullOrEmpty(cfg.Bgp.RouterId))
            {
                W(sb, $"   router-id {cfg.Bgp.RouterId}");
            }

            foreach (var neighbor in cfg.Bgp.Neighbors)
            {
                W(sb, $"   neighbor {neighbor.IpAddress} remote-as {neighbor.RemoteAs}");
                if (!string.IsNullOrEmpty(neighbor.Description))
                {
                    W(sb, $"   neighbor {neighbor.IpAddress} description {neighbor.Description}");
                }

                if (!string.IsNullOrEmpty(neighbor.Password))
                {
                    W(sb, $"   neighbor {neighbor.IpAddress} password {neighbor.Password}");
                }

                if (!string.IsNullOrEmpty(neighbor.UpdateSource))
                {
                    W(sb, $"   neighbor {neighbor.IpAddress} update-source {neighbor.UpdateSource}");
                }

                if (neighbor.EbgpMultihop > 0)
                {
                    W(sb, $"   neighbor {neighbor.IpAddress} ebgp-multihop {neighbor.EbgpMultihop}");
                }

                if (!string.IsNullOrEmpty(neighbor.RouteMapIn))
                {
                    W(sb, $"   neighbor {neighbor.IpAddress} route-map {neighbor.RouteMapIn} in");
                }

                if (!string.IsNullOrEmpty(neighbor.RouteMapOut))
                {
                    W(sb, $"   neighbor {neighbor.IpAddress} route-map {neighbor.RouteMapOut} out");
                }
            }

            foreach (var network in cfg.Bgp.Networks)
            {
                W(sb, $"   network {network}");
            }

            W(sb, "!");
        }

        W(sb, "!");
        sb.Append("end");
        return sb.ToString();
    }
}
