using System.Text;
using static Networker.Core.NetTools.Config.ConfigWriter;
using Networker.Core.Models.NetworkConfig;

namespace Networker.Core.NetTools.Config;

/// <summary>
/// Port of the Python <c>cisco_ios.j2</c> Jinja2 template. The reference
/// environment renders with <c>trim_blocks=True, lstrip_blocks=True</c>, so a
/// block tag at the end of a line (inline or standalone) drops the following
/// newline and the next rendered line provides the line terminator.
/// </summary>
internal static class CiscoIosConfigTemplate
{
    public static string Render(NetworkDeviceConfig cfg)
    {
        var sb = new StringBuilder();
        W(sb, "!");
        W(sb, "! Generated by NetConfigPro");
        W(sb, "! Vendor: Cisco IOS/IOS-XE");
        W(sb, "!");
        W(sb, $"hostname {cfg.Hostname}");
        W(sb, "!");

        if (!string.IsNullOrEmpty(cfg.EnableSecret))
        {
            W(sb, $"enable secret {cfg.EnableSecret}");
        }

        if (!string.IsNullOrEmpty(cfg.DomainName))
        {
            W(sb, $"ip domain-name {cfg.DomainName}");
        }

        W(sb, "!");

        if (cfg.DnsServers.Count > 0)
        {
            foreach (var dns in cfg.DnsServers)
            {
                W(sb, $"ip name-server {dns}");
            }

            W(sb, "!");
        }

        if (cfg.NtpServers.Count > 0)
        {
            foreach (var ntp in cfg.NtpServers)
            {
                W(sb, $"ntp server {ntp}");
            }

            W(sb, "!");
        }

        if (!string.IsNullOrEmpty(cfg.BannerMotd))
        {
            W(sb, "banner motd ^");
            W(sb, cfg.BannerMotd);
            W(sb, "^");
        }

        W(sb, "!");

        if (cfg.Stp is not null)
        {
            W(sb, $"spanning-tree mode {ConfigTemplateFilters.StpModeValue(cfg.Stp.Mode)}");
            if (cfg.Stp.Priority != 32768)
            {
                W(sb, $"spanning-tree vlan 1-4094 priority {cfg.Stp.Priority}");
            }

            foreach (var vlanId in cfg.Stp.RootPrimaryVlans)
            {
                W(sb, $"spanning-tree vlan {vlanId} root primary");
            }

            foreach (var vlanId in cfg.Stp.RootSecondaryVlans)
            {
                W(sb, $"spanning-tree vlan {vlanId} root secondary");
            }

            if (cfg.Stp.PortfastDefault)
            {
                W(sb, "spanning-tree portfast default");
            }

            if (cfg.Stp.BpduguardDefault)
            {
                W(sb, "spanning-tree portfast bpduguard default");
            }

            W(sb, "!");
        }

        if (cfg.Vlans.Count > 0)
        {
            foreach (var vlan in cfg.Vlans)
            {
                W(sb, $"vlan {vlan.VlanId}");
                W(sb, $" name {vlan.Name}");
                if (!string.IsNullOrEmpty(vlan.Description))
                {
                    W(sb, $" ! {vlan.Description}");
                }

                if (vlan.State != "active")
                {
                    W(sb, $" state {vlan.State}");
                }

                W(sb, "!");
            }
        }

        W(sb, "!");

        foreach (var iface in cfg.Interfaces)
        {
            W(sb, $"interface {iface.Name}");
            if (!string.IsNullOrEmpty(iface.Description))
            {
                W(sb, $" description {iface.Description}");
            }

            W(sb, iface.Enabled ? " no shutdown" : " shutdown");

            if (iface.SwitchportMode is not null)
            {
                if (iface.SwitchportMode == SwitchportMode.Access)
                {
                    W(sb, " switchport mode access");
                    if (iface.AccessVlan is not null)
                    {
                        W(sb, $" switchport access vlan {iface.AccessVlan}");
                    }

                    if (iface.VoiceVlan is not null)
                    {
                        W(sb, $" switchport voice vlan {iface.VoiceVlan}");
                    }
                }
                else if (iface.SwitchportMode == SwitchportMode.Trunk)
                {
                    W(sb, " switchport mode trunk");
                    if (iface.TrunkNativeVlan is not null)
                    {
                        W(sb, $" switchport trunk native vlan {iface.TrunkNativeVlan}");
                    }

                    if (!string.IsNullOrEmpty(iface.TrunkAllowedVlans))
                    {
                        W(sb, $" switchport trunk allowed vlan {iface.TrunkAllowedVlans}");
                    }
                }
                else
                {
                    W(sb, $" switchport mode {ConfigTemplateFilters.SwitchportModeValue(iface.SwitchportMode.Value)}");
                }
            }
            else if (iface.IsTrunk)
            {
                W(sb, " switchport mode trunk");
                if (iface.NativeVlan is not null)
                {
                    W(sb, $" switchport trunk native vlan {iface.NativeVlan}");
                }

                if (!string.IsNullOrEmpty(iface.TrunkAllowedVlans))
                {
                    W(sb, $" switchport trunk allowed vlan {iface.TrunkAllowedVlans}");
                }
            }
            else if (iface.VlanId is not null)
            {
                W(sb, " switchport mode access");
                W(sb, $" switchport access vlan {iface.VlanId}");
            }

            if (iface.IpAddress is not null && iface.SubnetMask is not null)
            {
                W(sb, $" ip address {iface.IpAddress} {iface.SubnetMask}");
            }

            if (!string.IsNullOrEmpty(iface.Speed))
            {
                W(sb, $" speed {iface.Speed}");
            }

            if (!string.IsNullOrEmpty(iface.Duplex))
            {
                W(sb, $" duplex {iface.Duplex}");
            }

            if (iface.Mtu != 1500)
            {
                W(sb, $" mtu {iface.Mtu}");
            }

            if (iface.ChannelGroup is not null)
            {
                W(sb, $" channel-group {iface.ChannelGroup} mode {(string.IsNullOrEmpty(iface.ChannelGroupMode) ? "active" : iface.ChannelGroupMode)}");
            }

            W(sb, "!");
        }

        W(sb, "!");

        foreach (var acl in cfg.Acls)
        {
            W(sb, acl.IsExtended
                ? $"ip access-list extended {acl.Name}"
                : $"ip access-list standard {acl.Name}");

            foreach (var entry in acl.Entries)
            {
                if (!string.IsNullOrEmpty(entry.Remark))
                {
                    W(sb, $" {entry.Sequence} remark {entry.Remark}");
                }
                else
                {
                    var line = new StringBuilder();
                    line.Append(' ').Append(entry.Sequence).Append(' ')
                        .Append(ConfigTemplateFilters.AclActionValue(entry.Action)).Append(' ')
                        .Append(ConfigTemplateFilters.AclProtocolValue(entry.Protocol)).Append(' ')
                        .Append(entry.Source);
                    if (entry.SourceWildcard != "0.0.0.0")
                    {
                        line.Append(' ').Append(entry.SourceWildcard);
                    }

                    if (!string.IsNullOrEmpty(entry.SourcePort))
                    {
                        line.Append(" eq ").Append(entry.SourcePort);
                    }

                    line.Append(' ').Append(entry.Destination);
                    if (entry.DestinationWildcard != "0.0.0.0")
                    {
                        line.Append(' ').Append(entry.DestinationWildcard);
                    }

                    if (!string.IsNullOrEmpty(entry.DestinationPort))
                    {
                        line.Append(" eq ").Append(entry.DestinationPort);
                    }

                    if (entry.Log)
                    {
                        line.Append(" log");
                    }

                    W(sb, line.ToString());
                }
            }

            W(sb, "!");
        }

        W(sb, "!");

        foreach (var route in cfg.StaticRoutes)
        {
            var line = new StringBuilder();
            line.Append("ip route ").Append(route.Destination).Append(' ')
                .Append(route.Mask).Append(' ').Append(route.NextHop);
            if (route.AdminDistance != 1)
            {
                line.Append(' ').Append(route.AdminDistance);
            }

            if (!string.IsNullOrEmpty(route.Name))
            {
                line.Append(" name ").Append(route.Name);
            }

            if (route.Permanent)
            {
                line.Append(" permanent");
            }

            W(sb, line.ToString());
        }

        W(sb, "!");

        foreach (var prefixList in cfg.PrefixLists)
        {
            foreach (var entry in prefixList.Entries)
            {
                var line = new StringBuilder();
                line.Append("ip prefix-list ").Append(prefixList.Name)
                    .Append(" seq ").Append(entry.Sequence).Append(' ')
                    .Append(entry.Action).Append(' ').Append(entry.Prefix);
                if (entry.Ge is not null)
                {
                    line.Append(" ge ").Append(entry.Ge);
                }

                if (entry.Le is not null)
                {
                    line.Append(" le ").Append(entry.Le);
                }

                W(sb, line.ToString());
            }
        }

        W(sb, "!");

        foreach (var routeMap in cfg.RouteMaps)
        {
            foreach (var entry in routeMap.Entries)
            {
                W(sb, $"route-map {routeMap.Name} {entry.Action} {entry.Sequence}");
                if (!string.IsNullOrEmpty(entry.MatchPrefixList))
                {
                    W(sb, $" match ip address prefix-list {entry.MatchPrefixList}");
                }

                if (!string.IsNullOrEmpty(entry.MatchAsPath))
                {
                    W(sb, $" match as-path {entry.MatchAsPath}");
                }

                if (!string.IsNullOrEmpty(entry.MatchCommunity))
                {
                    W(sb, $" match community {entry.MatchCommunity}");
                }

                if (entry.SetLocalPref is not null)
                {
                    W(sb, $" set local-preference {entry.SetLocalPref}");
                }

                if (entry.SetMed is not null)
                {
                    W(sb, $" set metric {entry.SetMed}");
                }

                if (entry.SetWeight is not null)
                {
                    W(sb, $" set weight {entry.SetWeight}");
                }

                if (!string.IsNullOrEmpty(entry.SetAsPathPrepend))
                {
                    W(sb, $" set as-path prepend {entry.SetAsPathPrepend}");
                }

                if (!string.IsNullOrEmpty(entry.SetCommunity))
                {
                    W(sb, $" set community {entry.SetCommunity}");
                }

                if (!string.IsNullOrEmpty(entry.SetNextHop))
                {
                    W(sb, $" set ip next-hop {entry.SetNextHop}");
                }

                W(sb, "!");
            }
        }

        W(sb, "!");

        if (cfg.Ospf is not null)
        {
            W(sb, $"router ospf {cfg.Ospf.ProcessId}");
            if (!string.IsNullOrEmpty(cfg.Ospf.RouterId))
            {
                W(sb, $" router-id {cfg.Ospf.RouterId}");
            }

            if (cfg.Ospf.ReferenceBandwidth != 100)
            {
                W(sb, $" auto-cost reference-bandwidth {cfg.Ospf.ReferenceBandwidth}");
            }

            foreach (var network in cfg.Ospf.Networks)
            {
                W(sb, $" network {network.Network} {network.Wildcard} area {network.Area}");
            }

            foreach (var passive in cfg.Ospf.PassiveInterfaces)
            {
                W(sb, $" passive-interface {passive}");
            }

            if (cfg.Ospf.DefaultInformationOriginate)
            {
                W(sb, " default-information originate");
            }

            W(sb, "!");
        }

        W(sb, "!");

        if (cfg.Eigrp is not null)
        {
            if (cfg.Eigrp.NamedMode)
            {
                W(sb, $"router eigrp {cfg.Eigrp.Name}");
                W(sb, " !");
                W(sb, $" address-family ipv4 unicast autonomous-system {cfg.Eigrp.AsNumber}");
                W(sb, "  !");
                if (!string.IsNullOrEmpty(cfg.Eigrp.RouterId))
                {
                    W(sb, $"  eigrp router-id {cfg.Eigrp.RouterId}");
                }

                foreach (var network in cfg.Eigrp.Networks)
                {
                    W(sb, network.Wildcard is not null
                        ? $"  network {network.Network} {network.Wildcard}"
                        : $"  network {network.Network}");
                }

                foreach (var passive in cfg.Eigrp.PassiveInterfaces)
                {
                    W(sb, $"  passive-interface {passive}");
                }

                foreach (var redist in cfg.Eigrp.Redistribute)
                {
                    W(sb, $"  redistribute {redist}");
                }

                W(sb, "  exit-address-family");
            }
            else
            {
                W(sb, $"router eigrp {cfg.Eigrp.AsNumber}");
                if (!string.IsNullOrEmpty(cfg.Eigrp.RouterId))
                {
                    W(sb, $" eigrp router-id {cfg.Eigrp.RouterId}");
                }

                if (!cfg.Eigrp.AutoSummary)
                {
                    W(sb, " no auto-summary");
                }

                foreach (var network in cfg.Eigrp.Networks)
                {
                    W(sb, network.Wildcard is not null
                        ? $" network {network.Network} {network.Wildcard}"
                        : $" network {network.Network}");
                }

                foreach (var passive in cfg.Eigrp.PassiveInterfaces)
                {
                    W(sb, $" passive-interface {passive}");
                }

                foreach (var redist in cfg.Eigrp.Redistribute)
                {
                    W(sb, $" redistribute {redist}");
                }
            }

            W(sb, "!");
        }

        W(sb, "!");

        if (cfg.Bgp is not null)
        {
            W(sb, $"router bgp {cfg.Bgp.LocalAs}");
            if (!string.IsNullOrEmpty(cfg.Bgp.RouterId))
            {
                W(sb, $" bgp router-id {cfg.Bgp.RouterId}");
            }

            if (cfg.Bgp.LogNeighborChanges)
            {
                W(sb, " bgp log-neighbor-changes");
            }

            foreach (var network in cfg.Bgp.Networks)
            {
                W(sb, $" network {network}");
            }

            foreach (var neighbor in cfg.Bgp.Neighbors)
            {
                W(sb, $" neighbor {neighbor.IpAddress} remote-as {neighbor.RemoteAs}");
                if (!string.IsNullOrEmpty(neighbor.Description))
                {
                    W(sb, $" neighbor {neighbor.IpAddress} description {neighbor.Description}");
                }

                if (!string.IsNullOrEmpty(neighbor.Password))
                {
                    W(sb, $" neighbor {neighbor.IpAddress} password {neighbor.Password}");
                }

                if (!string.IsNullOrEmpty(neighbor.UpdateSource))
                {
                    W(sb, $" neighbor {neighbor.IpAddress} update-source {neighbor.UpdateSource}");
                }

                if (neighbor.EbgpMultihop > 0)
                {
                    W(sb, $" neighbor {neighbor.IpAddress} ebgp-multihop {neighbor.EbgpMultihop}");
                }

                if (!string.IsNullOrEmpty(neighbor.RouteMapIn))
                {
                    W(sb, $" neighbor {neighbor.IpAddress} route-map {neighbor.RouteMapIn} in");
                }

                if (!string.IsNullOrEmpty(neighbor.RouteMapOut))
                {
                    W(sb, $" neighbor {neighbor.IpAddress} route-map {neighbor.RouteMapOut} out");
                }
            }

            W(sb, "!");
        }

        W(sb, "!");
        sb.Append("end");
        return sb.ToString();
    }
}
