using System.Text;
using Networker.Core.NetTools.Ip;

namespace Networker.Core.NetTools.Config;

/// <summary>
/// Deterministic configuration generation across vendor platforms. All output
/// derives from the same <see cref="DeviceSpec"/> so the same intent renders
/// on Cisco IOS-XE, Juniper Junos, Arista EOS, and VyOS.
/// </summary>
public static class ConfigGenerator
{
    public static string Generate(ConfigPlatform platform, DeviceSpec spec)
    {
        return platform switch
        {
            ConfigPlatform.CiscoIosXe => GenerateCiscoIosXe(spec),
            ConfigPlatform.JuniperJunos => GenerateJuniperJunos(spec),
            ConfigPlatform.AristaEos => GenerateAristaEos(spec),
            ConfigPlatform.Vyos => GenerateVyos(spec),
            _ => throw new ArgumentOutOfRangeException(nameof(platform)),
        };
    }

    public static string GenerateCiscoIosXe(DeviceSpec spec)
    {
        var sb = new StringBuilder();
        sb.AppendLine("! Generated by Networker Copilot");
        sb.AppendLine($"hostname {spec.Hostname}");
        sb.AppendLine("!");

        if (!string.IsNullOrWhiteSpace(spec.EnableSecret))
        {
            sb.AppendLine($"enable secret {spec.EnableSecret}");
        }

        sb.AppendLine("service password-encryption");

        if (!string.IsNullOrWhiteSpace(spec.DomainName))
        {
            sb.AppendLine($"ip domain-name {spec.DomainName}");
        }

        if (!string.IsNullOrWhiteSpace(spec.Username) && !string.IsNullOrWhiteSpace(spec.UsernameSecret))
        {
            sb.AppendLine($"username {spec.Username} privilege 15 secret {spec.UsernameSecret}");
        }

        sb.AppendLine("!");

        foreach (var vlan in spec.Vlans)
        {
            sb.AppendLine($"vlan {vlan.Id}");
            if (!string.IsNullOrWhiteSpace(vlan.Name))
            {
                sb.AppendLine($" name {vlan.Name}");
            }

            sb.AppendLine("!");
        }

        foreach (var vlan in spec.Vlans.Where(v => !string.IsNullOrWhiteSpace(v.InterfaceVlanIp)))
        {
            var (network, mask) = SplitCidr(vlan.InterfaceVlanIp!);
            sb.AppendLine($"interface Vlan{vlan.Id}");
            sb.AppendLine($" ip address {network} {mask}");
            sb.AppendLine("!");
        }

        foreach (var intf in spec.Interfaces)
        {
            sb.AppendLine($"interface {intf.Name}");
            if (!string.IsNullOrWhiteSpace(intf.Description))
            {
                sb.AppendLine($" description {intf.Description}");
            }

            if (!string.IsNullOrWhiteSpace(intf.Mtu))
            {
                sb.AppendLine($" mtu {intf.Mtu}");
            }

            if (intf.Mode is "access")
            {
                sb.AppendLine(" switchport mode access");
                if (!string.IsNullOrWhiteSpace(intf.Vlan))
                {
                    sb.AppendLine($" switchport access vlan {intf.Vlan}");
                }
            }
            else if (intf.Mode is "trunk")
            {
                sb.AppendLine(" switchport mode trunk");
                if (!string.IsNullOrWhiteSpace(intf.AllowedVlans))
                {
                    sb.AppendLine($" switchport trunk allowed vlan {intf.AllowedVlans}");
                }
            }
            else if (!string.IsNullOrWhiteSpace(intf.Ip))
            {
                var (network, mask) = SplitCidr(intf.Ip);
                sb.AppendLine($" ip address {network} {mask}");
            }

            sb.AppendLine(intf.Shutdown ? " shutdown" : " no shutdown");
            sb.AppendLine("!");
        }

        foreach (var group in spec.Acls.GroupBy(a => a.Name))
        {
            sb.AppendLine($"ip access-list extended {group.Key}");
            foreach (var entry in group)
            {
                sb.AppendLine($" {RenderAclEntry(entry)}");
            }

            sb.AppendLine("!");
        }

        if (spec.OspfAreas.Count > 0 || !string.IsNullOrWhiteSpace(spec.OspfProcessId))
        {
            var process = string.IsNullOrWhiteSpace(spec.OspfProcessId) ? "1" : spec.OspfProcessId;
            sb.AppendLine($"router ospf {process}");
            if (!string.IsNullOrWhiteSpace(spec.RouterId))
            {
                sb.AppendLine($" router-id {spec.RouterId}");
            }

            foreach (var area in spec.OspfAreas)
            {
                var subnet = IpToolkit.Calculate(area.Cidr);
                sb.AppendLine($" network {subnet.NetworkAddress} {subnet.WildcardMask} area {area.Area}");
            }

            sb.AppendLine("!");
        }

        if (!string.IsNullOrWhiteSpace(spec.BgpAsn))
        {
            sb.AppendLine($"router bgp {spec.BgpAsn}");
            if (!string.IsNullOrWhiteSpace(spec.RouterId))
            {
                sb.AppendLine($" bgp router-id {spec.RouterId}");
            }

            foreach (var neighbor in spec.BgpNeighbors)
            {
                sb.AppendLine($" neighbor {neighbor.PeerIp} remote-as {neighbor.RemoteAs}");
                if (!string.IsNullOrWhiteSpace(neighbor.Description))
                {
                    sb.AppendLine($" neighbor {neighbor.PeerIp} description {neighbor.Description}");
                }
            }

            foreach (var network in spec.BgpNetworks)
            {
                var subnet = IpToolkit.Calculate(network);
                sb.AppendLine($" network {subnet.NetworkAddress} mask {subnet.Netmask}");
            }

            if (spec.BgpRedistributeConnected)
            {
                sb.AppendLine(" redistribute connected");
            }

            sb.AppendLine("!");
        }

        AppendNat(sb, spec);
        AppendGlobalServices(sb, spec);
        sb.AppendLine("end");
        return sb.ToString();
    }

    public static string GenerateJuniperJunos(DeviceSpec spec)
    {
        var sb = new StringBuilder();
        sb.AppendLine("## Generated by Networker Copilot");
        sb.AppendLine($"set system host-name {spec.Hostname}");
        if (!string.IsNullOrWhiteSpace(spec.DomainName))
        {
            sb.AppendLine($"set system domain-name {spec.DomainName}");
        }

        if (!string.IsNullOrWhiteSpace(spec.EnableSecret))
        {
            sb.AppendLine($"set system root-authentication encrypted-password \"{spec.EnableSecret}\"");
        }

        if (!string.IsNullOrWhiteSpace(spec.Username) && !string.IsNullOrWhiteSpace(spec.UsernameSecret))
        {
            sb.AppendLine($"set system login user {spec.Username} class super-user authentication encrypted-password \"{spec.UsernameSecret}\"");
        }

        sb.AppendLine("set system services ssh");

        if (!string.IsNullOrWhiteSpace(spec.SnmpCommunity))
        {
            sb.AppendLine($"set snmp community {spec.SnmpCommunity}");
        }

        if (!string.IsNullOrWhiteSpace(spec.LoggingHost))
        {
            sb.AppendLine($"set system syslog host {spec.LoggingHost} any any");
        }

        if (!string.IsNullOrWhiteSpace(spec.NtpServer))
        {
            sb.AppendLine($"set system ntp server {spec.NtpServer}");
        }

        foreach (var vlan in spec.Vlans)
        {
            var name = string.IsNullOrWhiteSpace(vlan.Name) ? $"vlan{vlan.Id}" : vlan.Name;
            sb.AppendLine($"set vlans {name} vlan-id {vlan.Id}");
            if (!string.IsNullOrWhiteSpace(vlan.InterfaceVlanIp))
            {
                sb.AppendLine($"set vlans {name} l3-interface irb.{vlan.Id}");
                sb.AppendLine($"set interfaces irb unit {vlan.Id} family inet address {vlan.InterfaceVlanIp}");
            }
        }

        foreach (var intf in spec.Interfaces)
        {
            var unit = intf.Mode is "access" or "trunk"
                ? $"unit 0 family ethernet-switching"
                : $"unit 0 family inet";
            sb.AppendLine($"set interfaces {intf.Name} {unit}");

            if (!string.IsNullOrWhiteSpace(intf.Description))
            {
                sb.AppendLine($"set interfaces {intf.Name} description \"{intf.Description}\"");
            }

            if (!string.IsNullOrWhiteSpace(intf.Mtu))
            {
                sb.AppendLine($"set interfaces {intf.Name} unit 0 family ethernet-switching mtu {intf.Mtu}");
            }

            if (intf.Mode is "access")
            {
                sb.AppendLine($"set interfaces {intf.Name} unit 0 family ethernet-switching interface-mode access");
                if (!string.IsNullOrWhiteSpace(intf.Vlan))
                {
                    sb.AppendLine($"set interfaces {intf.Name} unit 0 family ethernet-switching vlan members {intf.Vlan}");
                }
            }
            else if (intf.Mode is "trunk")
            {
                sb.AppendLine($"set interfaces {intf.Name} unit 0 family ethernet-switching interface-mode trunk");
                var members = string.IsNullOrWhiteSpace(intf.AllowedVlans)
                    ? "all"
                    : intf.AllowedVlans;
                sb.AppendLine($"set interfaces {intf.Name} unit 0 family ethernet-switching vlan members {members}");
            }
            else if (!string.IsNullOrWhiteSpace(intf.Ip))
            {
                sb.AppendLine($"set interfaces {intf.Name} unit 0 family inet address {intf.Ip}");
            }

            if (intf.Shutdown)
            {
                sb.AppendLine($"set interfaces {intf.Name} disable");
            }
        }

        if (spec.OspfAreas.Count > 0)
        {
            foreach (var area in spec.OspfAreas)
            {
                var subnet = IpToolkit.Calculate(area.Cidr);
                sb.AppendLine($"set protocols ospf area {area.Area} network {subnet.NetworkAddress}/{subnet.PrefixLength}");
            }

            if (!string.IsNullOrWhiteSpace(spec.RouterId))
            {
                sb.AppendLine($"set protocols ospf parameters router-id {spec.RouterId}");
            }
        }

        if (!string.IsNullOrWhiteSpace(spec.BgpAsn))
        {
            sb.AppendLine($"set protocols bgp local-as {spec.BgpAsn}");
            sb.AppendLine("set policy-options policy-statement NETWORK-EXPORT term 10 from protocol static");
            sb.AppendLine("set policy-options policy-statement NETWORK-EXPORT term 10 then accept");

            if (spec.BgpRedistributeConnected)
            {
                sb.AppendLine("set policy-options policy-statement NETWORK-EXPORT term 11 from protocol direct");
                sb.AppendLine("set policy-options policy-statement NETWORK-EXPORT term 11 then accept");
            }

            sb.AppendLine("set protocols bgp group EXTERNAL type external");
            sb.AppendLine("set protocols bgp group EXTERNAL export NETWORK-EXPORT");
            foreach (var neighbor in spec.BgpNeighbors)
            {
                sb.AppendLine($"set protocols bgp group EXTERNAL neighbor {neighbor.PeerIp} peer-as {neighbor.RemoteAs}");
                if (!string.IsNullOrWhiteSpace(neighbor.Description))
                {
                    sb.AppendLine($"set protocols bgp group EXTERNAL neighbor {neighbor.PeerIp} description \"{neighbor.Description}\"");
                }
            }

            foreach (var network in spec.BgpNetworks)
            {
                sb.AppendLine($"set policy-options prefix-list ADVERTISED {network}");
            }
        }

        return sb.ToString();
    }

    public static string GenerateAristaEos(DeviceSpec spec)
    {
        var sb = new StringBuilder();
        sb.AppendLine("! Generated by Networker Copilot");
        sb.AppendLine($"hostname {spec.Hostname}");
        sb.AppendLine("!");

        if (!string.IsNullOrWhiteSpace(spec.Username) && !string.IsNullOrWhiteSpace(spec.UsernameSecret))
        {
            sb.AppendLine($"username {spec.Username} privilege 15 secret {spec.UsernameSecret}");
        }

        if (!string.IsNullOrWhiteSpace(spec.DomainName))
        {
            sb.AppendLine($"ip domain-name {spec.DomainName}");
        }

        sb.AppendLine("!");

        foreach (var vlan in spec.Vlans)
        {
            sb.AppendLine($"vlan {vlan.Id}");
            if (!string.IsNullOrWhiteSpace(vlan.Name))
            {
                sb.AppendLine($"   name {vlan.Name}");
            }

            if (!string.IsNullOrWhiteSpace(vlan.InterfaceVlanIp))
            {
                sb.AppendLine($"   ip address {vlan.InterfaceVlanIp}");
            }
        }

        sb.AppendLine("!");

        foreach (var intf in spec.Interfaces)
        {
            sb.AppendLine($"interface {intf.Name}");
            if (!string.IsNullOrWhiteSpace(intf.Description))
            {
                sb.AppendLine($"   description {intf.Description}");
            }

            if (!string.IsNullOrWhiteSpace(intf.Mtu))
            {
                sb.AppendLine($"   mtu {intf.Mtu}");
            }

            if (intf.Mode is "access")
            {
                sb.AppendLine("   switchport mode access");
                if (!string.IsNullOrWhiteSpace(intf.Vlan))
                {
                    sb.AppendLine($"   switchport access vlan {intf.Vlan}");
                }
            }
            else if (intf.Mode is "trunk")
            {
                sb.AppendLine("   switchport mode trunk");
                if (!string.IsNullOrWhiteSpace(intf.AllowedVlans))
                {
                    sb.AppendLine($"   switchport trunk allowed vlan {intf.AllowedVlans}");
                }
            }
            else if (!string.IsNullOrWhiteSpace(intf.Ip))
            {
                sb.AppendLine($"   no switchport");
                sb.AppendLine($"   ip address {intf.Ip}");
            }

            if (!string.IsNullOrWhiteSpace(intf.Speed))
            {
                sb.AppendLine($"   speed {intf.Speed}");
            }

            if (!string.IsNullOrWhiteSpace(intf.Duplex))
            {
                sb.AppendLine($"   duplex {intf.Duplex}");
            }

            sb.AppendLine(intf.Shutdown ? "   shutdown" : "   no shutdown");
        }

        sb.AppendLine("!");

        foreach (var group in spec.Acls.GroupBy(a => a.Name))
        {
            sb.AppendLine($"ip access-list {group.Key}");
            var seq = 10;
            foreach (var entry in group)
            {
                sb.AppendLine($"   {seq} {RenderAclEntry(entry)}");
                seq += 10;
            }
        }

        sb.AppendLine("!");

        if (spec.OspfAreas.Count > 0)
        {
            var process = string.IsNullOrWhiteSpace(spec.OspfProcessId) ? "1" : spec.OspfProcessId;
            sb.AppendLine($"router ospf {process}");
            if (!string.IsNullOrWhiteSpace(spec.RouterId))
            {
                sb.AppendLine($"   router-id {spec.RouterId}");
            }

            foreach (var area in spec.OspfAreas)
            {
                var subnet = IpToolkit.Calculate(area.Cidr);
                sb.AppendLine($"   network {subnet.NetworkAddress}/{subnet.PrefixLength} area {area.Area}");
            }
        }

        if (!string.IsNullOrWhiteSpace(spec.BgpAsn))
        {
            sb.AppendLine($"router bgp {spec.BgpAsn}");
            if (!string.IsNullOrWhiteSpace(spec.RouterId))
            {
                sb.AppendLine($"   router-id {spec.RouterId}");
            }

            foreach (var neighbor in spec.BgpNeighbors)
            {
                sb.AppendLine($"   neighbor {neighbor.PeerIp} remote-as {neighbor.RemoteAs}");
            }

            foreach (var network in spec.BgpNetworks)
            {
                sb.AppendLine($"   network {network}");
            }

            if (spec.BgpRedistributeConnected)
            {
                sb.AppendLine("   redistribute connected");
            }
        }

        sb.AppendLine("!");

        AppendNatEos(sb, spec);
        AppendGlobalServicesEos(sb, spec);
        return sb.ToString();
    }

    public static string GenerateVyos(DeviceSpec spec)
    {
        var sb = new StringBuilder();
        sb.AppendLine("# Generated by Networker Copilot");
        sb.AppendLine($"set system host-name '{spec.Hostname}'");
        if (!string.IsNullOrWhiteSpace(spec.DomainName))
        {
            sb.AppendLine($"set system domain-name '{spec.DomainName}'");
        }

        if (!string.IsNullOrWhiteSpace(spec.Username) && !string.IsNullOrWhiteSpace(spec.UsernameSecret))
        {
            sb.AppendLine($"set system login user {spec.Username} authentication encrypted-password '{spec.UsernameSecret}'");
            sb.AppendLine($"set system login user {spec.Username} level 15");
        }

        sb.AppendLine("set service ssh");

        if (!string.IsNullOrWhiteSpace(spec.SnmpCommunity))
        {
            sb.AppendLine($"set service snmp community '{spec.SnmpCommunity}'");
        }

        if (!string.IsNullOrWhiteSpace(spec.NtpServer))
        {
            sb.AppendLine($"set system ntp server {spec.NtpServer}");
        }

        foreach (var vlan in spec.Vlans)
        {
            foreach (var intf in spec.Interfaces.Where(i => i.Mode is "trunk" && !string.IsNullOrWhiteSpace(i.AllowedVlans)))
            {
                foreach (var id in intf.AllowedVlans!.Split(','))
                {
                    if (id.Trim() == vlan.Id)
                    {
                        sb.AppendLine($"set interfaces ethernet {intf.Name} vif {vlan.Id} description '{(string.IsNullOrWhiteSpace(vlan.Name) ? $"VLAN {vlan.Id}" : vlan.Name)}'");
                        if (!string.IsNullOrWhiteSpace(vlan.InterfaceVlanIp))
                        {
                            sb.AppendLine($"set interfaces ethernet {intf.Name} vif {vlan.Id} address {vlan.InterfaceVlanIp}");
                        }
                    }
                }
            }
        }

        foreach (var intf in spec.Interfaces)
        {
            sb.AppendLine($"set interfaces ethernet {intf.Name} description '{(intf.Description ?? string.Empty)}'");
            if (!string.IsNullOrWhiteSpace(intf.Mtu))
            {
                sb.AppendLine($"set interfaces ethernet {intf.Name} mtu {intf.Mtu}");
            }

            if (intf.Mode is "access")
            {
                if (!string.IsNullOrWhiteSpace(intf.Vlan))
                {
                    var vlanName = string.IsNullOrWhiteSpace(intf.Vlan)
                        ? $"VLAN {intf.Vlan}"
                        : $"VLAN {intf.Vlan}";
                    sb.AppendLine($"set interfaces ethernet {intf.Name} vif {intf.Vlan} description '{vlanName}'");
                    var svi = spec.Vlans.FirstOrDefault(v => v.Id == intf.Vlan && !string.IsNullOrWhiteSpace(v.InterfaceVlanIp));
                    if (svi is not null)
                    {
                        sb.AppendLine($"set interfaces ethernet {intf.Name} vif {intf.Vlan} address {svi.InterfaceVlanIp}");
                    }
                }
            }
            else if (intf.Mode is "trunk")
            {
                // vifs are emitted in the VLAN loop above.
            }
            else if (!string.IsNullOrWhiteSpace(intf.Ip))
            {
                sb.AppendLine($"set interfaces ethernet {intf.Name} address {intf.Ip}");
            }

            if (intf.Shutdown)
            {
                sb.AppendLine($"set interfaces ethernet {intf.Name} disable");
            }
        }

        if (spec.OspfAreas.Count > 0)
        {
            if (!string.IsNullOrWhiteSpace(spec.RouterId))
            {
                sb.AppendLine($"set protocols ospf parameters router-id {spec.RouterId}");
            }

            foreach (var area in spec.OspfAreas)
            {
                sb.AppendLine($"set protocols ospf area {area.Area} network {area.Cidr}");
            }
        }

        if (!string.IsNullOrWhiteSpace(spec.BgpAsn))
        {
            foreach (var neighbor in spec.BgpNeighbors)
            {
                sb.AppendLine($"set protocols bgp {spec.BgpAsn} neighbor {neighbor.PeerIp} remote-as '{neighbor.RemoteAs}'");
            }

            foreach (var network in spec.BgpNetworks)
            {
                sb.AppendLine($"set protocols bgp {spec.BgpAsn} network {network}");
            }

            if (spec.BgpRedistributeConnected)
            {
                sb.AppendLine($"set protocols bgp {spec.BgpAsn} redistribute connected");
            }
        }

        return sb.ToString();
    }

    private static (string Ip, string Mask) SplitCidr(string cidr)
    {
        var subnet = IpToolkit.Calculate(cidr);
        return (cidr.Split('/')[0], subnet.Netmask);
    }

    private static string RenderAclEntry(AclEntrySpec entry)
    {
        var sb = new StringBuilder(entry.Action);
        sb.Append(' ').Append(string.IsNullOrWhiteSpace(entry.Protocol) ? "ip" : entry.Protocol);
        sb.Append(' ').Append(string.IsNullOrWhiteSpace(entry.Source) ? "any" : entry.Source);
        if (!string.IsNullOrWhiteSpace(entry.SourcePort))
        {
            sb.Append(" eq ").Append(entry.SourcePort);
        }

        sb.Append(' ').Append(string.IsNullOrWhiteSpace(entry.Destination) ? "any" : entry.Destination);
        if (!string.IsNullOrWhiteSpace(entry.DestinationPort))
        {
            sb.Append(" eq ").Append(entry.DestinationPort);
        }

        if (entry.Established)
        {
            sb.Append(" established");
        }

        if (entry.Log)
        {
            sb.Append(" log");
        }

        return sb.ToString();
    }

    private static void AppendNat(StringBuilder sb, DeviceSpec spec)
    {
        if (spec.Nat is null)
        {
            return;
        }

        foreach (var inside in spec.Nat.Inside)
        {
            sb.AppendLine($"interface {inside}");
            sb.AppendLine(" ip nat inside");
            sb.AppendLine("!");
        }

        if (!string.IsNullOrWhiteSpace(spec.Nat.Outside))
        {
            sb.AppendLine($"interface {spec.Nat.Outside}");
            sb.AppendLine(" ip nat outside");
            sb.AppendLine("!");
        }

        var aclName = string.IsNullOrWhiteSpace(spec.Nat.AclName) ? "NAT-ACL" : spec.Nat.AclName;
        sb.AppendLine($"ip access-list standard {aclName}");
        sb.AppendLine(" permit any");
        sb.AppendLine("!");

        if (!string.IsNullOrWhiteSpace(spec.Nat.PoolStart) && !string.IsNullOrWhiteSpace(spec.Nat.PoolEnd))
        {
            var mask = string.IsNullOrWhiteSpace(spec.Nat.PoolMask) ? "255.255.255.0" : spec.Nat.PoolMask;
            sb.AppendLine($"ip nat pool NAT-POOL {spec.Nat.PoolStart} {spec.Nat.PoolEnd} netmask {mask}");
            sb.AppendLine($"ip nat inside source list {aclName} pool NAT-POOL overload");
        }
        else
        {
            sb.AppendLine($"ip nat inside source list {aclName} interface overload");
        }

        sb.AppendLine("!");
    }

    private static void AppendNatEos(StringBuilder sb, DeviceSpec spec)
    {
        if (spec.Nat is null)
        {
            return;
        }

        foreach (var inside in spec.Nat.Inside)
        {
            sb.AppendLine($"interface {inside}");
            sb.AppendLine("   ip nat inside");
        }

        if (!string.IsNullOrWhiteSpace(spec.Nat.Outside))
        {
            sb.AppendLine($"interface {spec.Nat.Outside}");
            sb.AppendLine("   ip nat outside");
        }

        var aclName = string.IsNullOrWhiteSpace(spec.Nat.AclName) ? "NAT-ACL" : spec.Nat.AclName;
        sb.AppendLine($"ip access-list {aclName}");
        sb.AppendLine("   10 permit ip any any");
        sb.AppendLine($"ip nat inside source list {aclName} interface overload");
        sb.AppendLine("!");
    }

    private static void AppendGlobalServices(StringBuilder sb, DeviceSpec spec)
    {
        if (!string.IsNullOrWhiteSpace(spec.SnmpCommunity))
        {
            sb.AppendLine($"snmp-server community {spec.SnmpCommunity} RO");
        }

        if (!string.IsNullOrWhiteSpace(spec.LoggingHost))
        {
            sb.AppendLine($"logging host {spec.LoggingHost}");
        }

        if (!string.IsNullOrWhiteSpace(spec.NtpServer))
        {
            sb.AppendLine($"ntp server {spec.NtpServer}");
        }

        sb.AppendLine("!");
    }

    private static void AppendGlobalServicesEos(StringBuilder sb, DeviceSpec spec)
    {
        if (!string.IsNullOrWhiteSpace(spec.SnmpCommunity))
        {
            sb.AppendLine($"snmp-server community {spec.SnmpCommunity} ro");
        }

        if (!string.IsNullOrWhiteSpace(spec.LoggingHost))
        {
            sb.AppendLine($"logging host {spec.LoggingHost}");
        }

        if (!string.IsNullOrWhiteSpace(spec.NtpServer))
        {
            sb.AppendLine($"ntp server {spec.NtpServer}");
        }

        sb.AppendLine("!");
    }
}

