using System.Text;
using static Networker.Core.NetTools.Config.ConfigWriter;
using Networker.Core.Models.NetworkConfig;

namespace Networker.Core.NetTools.Config;

/// <summary>
/// Port of the Python <c>juniper_junos.j2</c> Jinja2 template.
/// </summary>
internal static class JuniperJunosConfigTemplate
{
    public static string Render(NetworkDeviceConfig cfg)
    {
        var sb = new StringBuilder();
        W(sb, "## Generated by NetConfigPro");
        W(sb, "## Vendor: Juniper Junos");
        W(sb, "");

        W(sb, "system {");
        W(sb, $"    host-name {cfg.Hostname};");
        if (!string.IsNullOrEmpty(cfg.DomainName))
        {
            W(sb, $"    domain-name {cfg.DomainName};");
        }

        if (cfg.DnsServers.Count > 0)
        {
            W(sb, "    name-server {");
            foreach (var dns in cfg.DnsServers)
            {
                W(sb, $"        {dns};");
            }

            W(sb, "    }");
        }

        if (cfg.NtpServers.Count > 0)
        {
            W(sb, "    ntp {");
            foreach (var ntp in cfg.NtpServers)
            {
                W(sb, $"        server {ntp};");
            }

            W(sb, "    }");
        }

        if (!string.IsNullOrEmpty(cfg.EnableSecret))
        {
            W(sb, "    root-authentication {");
            W(sb, $"        encrypted-password \"{cfg.EnableSecret}\";");
            W(sb, "    }");
        }

        if (!string.IsNullOrEmpty(cfg.BannerMotd))
        {
            W(sb, "    login {");
            W(sb, $"        message \"{cfg.BannerMotd}\";");
            W(sb, "    }");
        }

        W(sb, "}");
        W(sb, "");

        if (cfg.Vlans.Count > 0)
        {
            W(sb, "vlans {");
            foreach (var vlan in cfg.Vlans)
            {
                W(sb, $"    {vlan.Name} {{");
                W(sb, $"        vlan-id {vlan.VlanId};");
                if (!string.IsNullOrEmpty(vlan.Description))
                {
                    W(sb, $"        description \"{vlan.Description}\";");
                }

                W(sb, "    }");
            }

            W(sb, "}");
        }

        W(sb, "");

        W(sb, "interfaces {");
        foreach (var iface in cfg.Interfaces)
        {
            W(sb, $"    {ConfigTemplateFilters.JunosInterfaceName(iface.Name)} {{");
            if (!string.IsNullOrEmpty(iface.Description))
            {
                W(sb, $"        description \"{iface.Description}\";");
            }

            if (!iface.Enabled)
            {
                W(sb, "        disable;");
            }

            if (iface.Mtu != 1500)
            {
                W(sb, $"        mtu {iface.Mtu};");
            }

            if (iface.ChannelGroup is not null)
            {
                W(sb, "        ether-options {");
                W(sb, $"            802.3ad ae{iface.ChannelGroup};");
                W(sb, "        }");
            }

            if (iface.IsTrunk)
            {
                W(sb, "        unit 0 {");
                W(sb, "            family ethernet-switching {");
                W(sb, "                port-mode trunk;");
                if (!string.IsNullOrEmpty(iface.TrunkAllowedVlans))
                {
                    W(sb, "                vlan {");
                    W(sb, $"                    members [ {iface.TrunkAllowedVlans} ];");
                    W(sb, "                }");
                }

                if (iface.NativeVlan is not null)
                {
                    W(sb, $"                native-vlan-id {iface.NativeVlan};");
                }

                W(sb, "            }");
                W(sb, "        }");
            }
            else if (iface.VlanId is not null)
            {
                W(sb, "        unit 0 {");
                W(sb, "            family ethernet-switching {");
                W(sb, "                port-mode access;");
                W(sb, "                vlan {");
                W(sb, $"                    members vlan{iface.VlanId};");
                W(sb, "                }");
                W(sb, "            }");
                W(sb, "        }");
            }
            else if (iface.IpAddress is not null && iface.SubnetMask is not null)
            {
                W(sb, "        unit 0 {");
                W(sb, "            family inet {");
                W(sb, $"                address {iface.IpAddress}/{ConfigTemplateFilters.SubnetToCidr(iface.SubnetMask.ToString())};");
                W(sb, "            }");
                W(sb, "        }");
            }

            W(sb, "    }");
        }

        W(sb, "}");
        W(sb, "");

        W(sb, "routing-options {");
        if (cfg.StaticRoutes.Count > 0)
        {
            W(sb, "    static {");
            foreach (var route in cfg.StaticRoutes)
            {
                W(sb, $"        route {route.Destination}/{ConfigTemplateFilters.SubnetToCidr(route.Mask)} {{");
                W(sb, $"            next-hop {route.NextHop};");
                if (route.AdminDistance != 1)
                {
                    W(sb, $"            preference {route.AdminDistance};");
                }

                if (route.Permanent)
                {
                    W(sb, "            retain;");
                }

                W(sb, "        }");
            }

            W(sb, "    }");
        }

        if (cfg.Bgp is not null)
        {
            W(sb, $"    autonomous-system {cfg.Bgp.LocalAs};");
        }

        if (cfg.Ospf is not null && !string.IsNullOrEmpty(cfg.Ospf.RouterId))
        {
            W(sb, $"    router-id {cfg.Ospf.RouterId};");
        }
        else if (cfg.Bgp is not null && !string.IsNullOrEmpty(cfg.Bgp.RouterId))
        {
            W(sb, $"    router-id {cfg.Bgp.RouterId};");
        }

        W(sb, "}");
        W(sb, "");

        if (cfg.Ospf is not null)
        {
            W(sb, "protocols {");
            W(sb, "    ospf {");
            if (cfg.Ospf.ReferenceBandwidth != 100)
            {
                W(sb, $"        reference-bandwidth {cfg.Ospf.ReferenceBandwidth}m;");
            }

            var areasSeen = new List<string>();
            foreach (var network in cfg.Ospf.Networks)
            {
                var areaDotted = network.Area < 256 ? $"0.0.0.{network.Area}" : network.Area.ToString();
                if (areasSeen.Contains(areaDotted))
                {
                    continue;
                }

                areasSeen.Add(areaDotted);
                W(sb, $"        area {areaDotted} {{");
                foreach (var net in cfg.Ospf.Networks)
                {
                    var netAreaDotted = net.Area < 256 ? $"0.0.0.{net.Area}" : net.Area.ToString();
                    if (netAreaDotted != areaDotted)
                    {
                        continue;
                    }

                    W(sb, $"            interface {ConfigTemplateFilters.JunosInterfaceName(net.Network)}.0 {{");
                    if (cfg.Ospf.PassiveInterfaces.Contains(net.Network))
                    {
                        W(sb, "                passive;");
                    }

                    W(sb, "            }");
                }

                W(sb, "        }");
            }

            W(sb, "    }");
            W(sb, "}");
        }

        W(sb, "");

        if (cfg.Bgp is not null)
        {
            W(sb, "protocols {");
            W(sb, "    bgp {");
            if (cfg.Bgp.LogNeighborChanges)
            {
                W(sb, "        log-updown;");
            }

            foreach (var neighbor in cfg.Bgp.Neighbors)
            {
                var isIbgp = neighbor.RemoteAs == cfg.Bgp.LocalAs;
                var groupName = string.IsNullOrEmpty(neighbor.Description)
                    ? "peer"
                    : neighbor.Description.Replace(' ', '_').Replace('-', '_');
                W(sb, $"        group {groupName} {{");
                W(sb, $"            type {(isIbgp ? "internal" : "external")};");
                if (!isIbgp)
                {
                    W(sb, $"            peer-as {neighbor.RemoteAs};");
                }

                if (!string.IsNullOrEmpty(neighbor.UpdateSource))
                {
                    W(sb, $"            local-address {neighbor.UpdateSource};");
                }

                if (neighbor.EbgpMultihop > 0 && !isIbgp)
                {
                    W(sb, "            multihop {");
                    W(sb, $"                ttl {neighbor.EbgpMultihop};");
                    W(sb, "            }");
                }

                W(sb, $"            neighbor {neighbor.IpAddress} {{");
                if (!string.IsNullOrEmpty(neighbor.Description))
                {
                    W(sb, $"                description \"{neighbor.Description}\";");
                }

                if (!string.IsNullOrEmpty(neighbor.Password))
                {
                    W(sb, $"                authentication-key \"{neighbor.Password}\";");
                }

                if (!string.IsNullOrEmpty(neighbor.RouteMapIn))
                {
                    W(sb, $"                import {neighbor.RouteMapIn};");
                }

                if (!string.IsNullOrEmpty(neighbor.RouteMapOut))
                {
                    W(sb, $"                export {neighbor.RouteMapOut};");
                }

                W(sb, "            }");
                W(sb, "        }");
            }

            W(sb, "    }");
            W(sb, "}");
        }

        W(sb, "");

        if (cfg.Acls.Count > 0)
        {
            W(sb, "firewall {");
            foreach (var acl in cfg.Acls)
            {
                W(sb, "    family inet {");
                W(sb, $"        filter {acl.Name} {{");
                foreach (var entry in acl.Entries)
                {
                    if (!string.IsNullOrEmpty(entry.Remark))
                    {
                        W(sb, $"            /* {entry.Remark} */");
                    }
                    else
                    {
                        W(sb, $"            term rule-{entry.Sequence} {{");
                        W(sb, "                from {");
                        if (entry.Protocol != AclProtocol.Ip)
                        {
                            W(sb, $"                    protocol {ConfigTemplateFilters.AclProtocolValue(entry.Protocol)};");
                        }

                        if (entry.Source != "any")
                        {
                            W(sb, $"                    source-address {entry.Source}/{ConfigTemplateFilters.SubnetToCidr(entry.SourceWildcard)};");
                        }

                        if (entry.Destination != "any")
                        {
                            W(sb, $"                    destination-address {entry.Destination}/{ConfigTemplateFilters.SubnetToCidr(entry.DestinationWildcard)};");
                        }

                        if (!string.IsNullOrEmpty(entry.SourcePort))
                        {
                            W(sb, $"                    source-port {entry.SourcePort};");
                        }

                        if (!string.IsNullOrEmpty(entry.DestinationPort))
                        {
                            W(sb, $"                    destination-port {entry.DestinationPort};");
                        }

                        W(sb, "                }");
                        W(sb, "                then {");
                        W(sb, entry.Action == AclAction.Permit ? "                    accept;" : "                    discard;");
                        if (entry.Log)
                        {
                            W(sb, "                    log;");
                        }

                        W(sb, "                }");
                        W(sb, "            }");
                    }
                }

                W(sb, "        }");
                W(sb, "    }");
            }

            sb.Append("}\n");
        }

        return sb.ToString();
    }
}
